### ISSUE TITLE
Touchscreen rotation with Lenovo Yoga 

### ISSUE THREAD

**Issue by JeanSchoeller** [JeanSchoeller/iio-hyprland#1]
> @RandomLegend
> 
> i found your package, works beautifully! However, it doesn't rotate the touchinput with it....so i am using a Lenovo Yoga that has a touchscreen that can be flipped 180° to transform into a big tablet.
> 
> I'd love to have it in portrait mode when flipped, but as of right now i'd have to manually change the touchinput. Could you insert that in your package aswell? That IF there is a touchscreen, that should be rotated in the same manner as the monitor orientation.
> 
> That would be awesome!
> 
> I can't open an issue on your project...is it disabled?
> 
> I updated it, and sadly it does not work
> 
> _Originally posted by @RandomLegend in https://github.com/hyprwm/Hyprland/issues/1588#issuecomment-1445239140_

Could you post the result of `hyprctl devices | grep touch` here? Thank you. It works on my Surface so I must have entered the wrong touch device in the code.

**Comment by RandomLegend** [comment]
Forget it...my yay was just dumb and didn't update your package correctly.

After building from source it now works as intendet. Thank you very much and sorry for the hassle....
Can be closed
