### ISSUE TITLE
[Bug] Not working with special category

### ISSUE THREAD

**Issue by short-circuit** [JeanSchoeller/iio-hyprland#13]
Running iio-hyprland spits out following into stdout:
```
ok
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
```
I got the screen rotation working by adding a fixed monitor in `hyprland.conf`, but touch and stylus do not work.
It seems that `hyprctl` changed how to set ids.

This is running on a:
`ASUS ROG Flow X13 GV301RE`

In KDE rotation of screen and digitizers work correctly.

EDIT:
seems like the keyword changed.
To set rotation on touch and tablet the following commands will do the trick:
```
hyprctl keyword input:touchdevice:transform $d
hyprctl keyword input:tablet:transform $d
```

Maybe it's also a good idea to run it in the `batch` command mode of `hyprctl`?

**Comment by tofeeh** [comment]
That break is confusing for everyone else. That update rotates a particular category but removes rotation from devices appropriately assigned as tablets and touch.
