### ISSUE TITLE
won't run on Lenovo Yoga 7 14ACN6

### ISSUE THREAD

**Issue by Ceye4n** [JeanSchoeller/iio-hyprland#27]
the exec-once doesn't seem to work, specifying the monitor doesn't help
if I run `iio-hyprland` in the terminal, it closes with the output

```
sh: line 1: jq: command not found
fgets: Resource temporarily unavailable
error: cannot get monitor ID for eDP-1
dbus[2311]: Applications must not close shared connections - see dbus_connection_close() docs. This is a bug in the application.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

**Comment by ipg0** [comment]
@Ceye4n I can see two issues:
## You don't have `jq` installed.
`jq` is a commandline JSON utility. If you're on Arch, run `sudo pacman -S jq`

## `iio-hyprland` can't find the monitor named `eDP-1`.
`eDP-1` is what the builtin monitor is called on most laptops, but it seems like yours is not.
To find out what yours is called, unplug all external monitors from your laptop and run `hyprctl monitors`.
It should print out something like this:
```
Monitor eDP-1 (ID 0):
	1920x1200@60.00300 at -1920x0
	description: BOE 0x0964
	make: BOE
	model: 0x0964
	serial: 
	active workspace: 11 (11)
	special workspace: 0 ()
	reserved: 0 40 0 0
	scale: 1.00
	transform: 2
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	mirrorOf: none
	availableModes: 1920x1200@60.00Hz 1920x1200@48.00Hz
```
Take the name of the monitor from the first line of the output after the word `Monitor` (you can see mine is actually called eDP-1). Then run `iio-hyprland <monitor-name>` and it should work correctly.

**Comment by Ceye4n** [comment]
thank you, everything works now
