### ISSUE TITLE
Support for Lenovo X1 Yoga touch

### ISSUE THREAD

**Issue by mrPaga** [JeanSchoeller/iio-hyprland#4]
Hi,

first of, thanks a lot for your work. It's incredibly useful!

It just miss the support for the newer lenovo x1 yoga touch stuff (wacom-hid-52b5-pen and wacom-hid-52b5-finger). 

I manually added them in my local repo and tested the changes. Here is the git diff patch [patch.txt](https://github.com/JeanSchoeller/iio-hyprland/files/11406192/patch.txt) if you want to add it to the repo for others.

Thanks again!

**Comment by JeanSchoeller** [comment]
Added thank you.
