### ISSUE TITLE
Not working on surface pro

### ISSUE THREAD

**Issue by waldoeGeek** [JeanSchoeller/iio-hyprland#5]
Doesn't seem to work on surface pro 7. Idk what info you need. Readme.md indicates the following.

output of hyprctl devices:

```
mice:
	Mouse at 76daecd0:
		microsoft-surface-type-cover-mouse
			default speed: 0.000000
	Mouse at 76c55400:
		microsoft-surface-type-cover-consumer-control-1
			default speed: 0.000000
	Mouse at 76db4f40:
		microsoft-surface-type-cover-touchpad
			default speed: 0.000000
Keyboards:
	Keyboard at 76ca3ac0:
		video-bus
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 76c88540:
		microsoft-surface-type-cover-keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 76c80740:
		microsoft-surface-type-cover-consumer-control
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 76c524a0:
		gpio-keys
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 76c45d50:
		gpio-keys-1
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: no
	Keyboard at 7880f0f0:
		surface-pen-keyboard
			rules: r "", m "", l "us", v "", o ""
			active keymap: English (US)
			main: yes
Tablets:
	Tablet at 76da02f0:
		ipts-045e:099f-stylus
	Tablet at 76ded500:
		ipts-stylus
Touch:
	Touch Device at 76c89c10:
		ipts-045e:099f-touchscreen
	Touch Device at 76b13e30:
		ipts-045e:099f
	Touch Device at 76c58c10:
		ipts-touch
Switches:
	Switch Device at 76c91b70:
		Lid Switch
	Switch Device at 76c5c290:
		Microsoft Surface Type Cover Tablet Mode Switch

```

**Comment by JeanSchoeller** [comment]
Can you give me the input of hyprctl monitors?

**Comment by RevolverUnit** [comment]
Not OP, but I'm also having issues with my Surface Pro 7. Here's my hyprctl monitors output if that helps.

```
Monitor eDP-1 (ID 0):  
        2736x1824@59.959000 at 0x0
        description: LG Display 0x0555 0x100000A1 (eDP-1)
        make: LG Display
        model: 0x0555
        serial: 0x100000A1
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 50 0 0
        scale: 1.00
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
```

It seems iio-hyprland rotates the touch screen input, but doesn't rotate the display itself.

**Comment by JeanSchoeller** [comment]
Quick question, did you build from source or did you build from package manager. Still need to update the package on AUR.

**Comment by RevolverUnit** [comment]
The first time I installed the AUR package, but I just now built it from the source and reinstalled it but still have the same issue.

**Comment by RevolverUnit** [comment]
Nevermind, I figured it out. It _was_ my configuration. I forgot to put "eDP-1" in my monitor configuration. Hopefully this helps you out @waldoeGeek .

**Comment by milesdm** [comment]
@RevolverUnit AH,HA!  I wasn't sure what you meant at first, but I added this to my hyprland.conf (I had no monitor line previously)

monitor=eDP-1,preferred,auto,2,transform,0

My guess is the default transform of 0 (normal) is what does the trick.

Thank you!

**Comment by JeanSchoeller** [comment]
@waldoeGeek Any chance this also fixed your issue?
I will add a line to the README to mention this.

**Comment by BurgerBrob** [comment]
I tried this on my surface pro 7 in august and it didn't work back then. Tried it out today again today and it seems to work. Idk what change fixed it but it works, all that matters. 

> @waldoeGeek Any chance this also fixed your issue? I will add a line to the README to mention this.

**Comment by BurgerBrob** [comment]
ok after reading the conversation in here I tried commenting the monitor lines and yeah seems like this causes the rotation not to work. I didn't have any `transform, 0` at the end though. My monitor is written as `monitor=eDP-1, preferred, auto, auto`

**Comment by BurgerBrob** [comment]
Though weirdly back when I tried it last time I am 99% sure I also had the `monitor=`, because the surface pro 7 has high hidpi and therefore needs scaling to be useable

**Comment by JeanSchoeller** [comment]
> Though weirdly back when I tried it last time I am 99% sure I also had the `monitor=`, because the surface pro 7 has high hidpi and therefore needs scaling to be useable

But did you use the eDP-1 name or leave it empty?
Hyprland wiki doesn't specify it I believe.
