### ISSUE TITLE
Adding support for Lenovo Thinkpad L13 Yoga Gen 3

### ISSUE THREAD

**Issue by matt1432** [JeanSchoeller/iio-hyprland#9]
Here are the inputs to support my laptop. Thank you for your work!
```
Tablets:
	Tablet at 561e295b7260:
		wacom-hid-52eb-pen


Touch:
	Touch Device at 561e295cad30:
		wacom-hid-52eb-finger
```

I also have a suggestion. It would be nice to be able to run the command with a '-d' flag for example where we could list the input devices in the terminal instead of having them baked in the code.

**Comment by JeanSchoeller** [comment]
Good idea. I was looking for a bit to move to Rust and let the code recognise the device. Somehow harder than it looks.
I will add the support for your computer ASAP.
